# Generated by Django 3.2.7 on 2022-01-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='join_body',
        ),
        migrations.RemoveField(
            model_name='project',
            name='source_link',
        ),
    ]
